# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HjnQ2-UtUmABF-DEMwfzI_MR6KVKC1jL
"""

import pandas as pd

df = pd.DataFrame ({ 'Ism': ['Merojiddin','Shuxratjon', 'Nurmuhammad','Muxammadaziz','Kamron','Oybek','Ogabek','Oyatbek','Xurjidbek','Shoxruxbek' ],
 'Familiya': ['Baxtiyorjonov', 'Shamshiddinov','Jumanazarov','Rozaliyev','Olimov','Akramov','Malikov','Qodirov','Odilov','Salimov'],
 'Yoshi': ['19','19','19','19','20','19','20','19','19','19'],
'Kursi':['2','2','2','2','2','2','2','2','2','2'],
})
print(df)

df.to_excel('best boys.xlsx', index=False, sheet_name='sheet1')